apiVersion: v1
kind: Service
metadata:
  name: Assignment3
  labels:
    app: Assignment3
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: Assignment3
